<style scoped>
    .currentjob a{
        /*	display:block;*/
    }
</style>
<?php
$this->headScript()->appendScript('');
?>
<body data-demo-id="chart" data-library="dom">
    <div id="main">

        <div style="text-align: center;">
            <div>
                <input type="text" name="selectDate" id="selectDate" class="clsdate valid" size="10">
                <input type="button" onclick="getanswers()" class="btn btn-success" name="Get" value="Get">
            </div>
            <div class="dtls">
                
            </div>
        </div>

    </div>
</body>
