<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="<?= $this->baseUrl("admin") ?>">
            <i class="icon-white icon-home" style="position:relative; top:5px;"></i>
            SEDD Admin
        </a>
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse">


                <ul class="nav">
                    <?php
                    $arrPerms = $this->checkLinkPerms('admin', 'contracts', 'all');
                    if ($arrPerms['allowMainLink']):
                        ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">contracts <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li class="<?= (preg_match('/^currentCont/', $this->activepage)) ? 'active' : '' ?>">
                                    <a href="<?= $this->baseUrl('/admin/contracts') ?>">current contracts</a>
                                </li>
                                <li class="<?= (preg_match('/^completedCon/', $this->activepage)) ? 'active' : '' ?>">
                                    <a href="<?= $this->baseUrl('/admin/contracts/completed') ?>">completed contracts</a>
                                </li>
                                <li class="divider"></li>
                                <li class="<?= (preg_match('/^addCon/', $this->activepage)) ? 'active' : '' ?>">
                                    <a href="<?= $this->baseUrl('/admin/contracts/add') ?>">new contract</a>
                                </li>
                            </ul>
                        </li>
                    <?php endif; ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">drills <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<?= (preg_match('/^currentDrills/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/drills') ?>">current drills</a>
                            </li>
                            <li class="<?= (preg_match('/^upcomingDrills/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/drills/upcoming') ?>">upcoming drills</a>
                            </li>
                            <li class="<?= (preg_match('/^completedDrills/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/drills/completed') ?>">completed drills</a>
                            </li>
                            <li class="divider"></li>
                            <li class="<?= (preg_match('/^addDrill/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/drills/add') ?>">new drill</a>
                            </li>
                            <li class="divider"></li>
                            <!--                            <li>
                                                            <a href="<?= $this->baseUrl('/rigmap') ?>">rigmap</a>
                                                        </li>-->
                            <li class="<?= (preg_match('/^yardReports/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/yard/reports') ?>">yard reports</a>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">crew <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <!--                            <li>
                                                            <a href="<?= $this->baseUrl('/admin/crew/listall') ?>">all crew</a>
                                                        </li>
                                                        <li>
                                                            <a href="<?= $this->baseUrl('/admin/crew/idle') ?>">idle crew</a>
                                                        </li>
                                                        <li>
                                                            <a href="<?= $this->baseUrl('/admin/crew/idle') ?>">assigned crew</a>
                                                        </li>-->
                            <li class="<?= (preg_match('/^addCrew/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crew/add') ?>">new crew</a>
                            </li>
                            <li class="<?= (preg_match('/^managecwcm/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crew/managecwcm') ?>">manage crew - crew members</a>
                            </li>
                            <li class="<?= (preg_match('/^mapCrew/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crew/map-crew-rig') ?>">map crew - rig</a>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">crew members<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<?= (preg_match('/^listall/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crewmembers/listall') ?>">all crew members <?php echo $this->activepage; ?></a>
                                <!--                            </li>
                                                            <li>
                                                                <a href="<?= $this->baseUrl('/admin/crewmembers/idle') ?>">idle crew members</a>
                                                            </li>
                                                            <li>
                                                                <a href="<?= $this->baseUrl('/admin/crewmembers/idle') ?>">assigned crew members</a>
                                                            </li>-->
                            </li>
                            <li class="divider"></li>
                            <li class="<?= (preg_match('/^cmadd/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crewmembers/add') ?>">new crew member</a>
                            </li>
                            <li class="<?= (preg_match('/^managecwcm/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crew/managecwcm') ?>">manage crew - crew members</a>
                            </li>
                            <li class="<?= (preg_match('/^vpo/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crewmembers/compaircm') ?>">vpo</a>
                            </li>
                            <li class="<?= (preg_match('/^idle/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/crewmembers/get-idle-list') ?>">idle crew members</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">payroll<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<?= (preg_match('/^emptimecard/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/report/emptimecard') ?>">timecard</a>
                            </li>
                            <!--                            <li>
                                                            <a href="<?= $this->baseUrl('/admin/report/flextimecard') ?>">timecard</a>
                                                        </li>-->
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">equipment<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<?= (preg_match('/^manageqt/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/equipment/manageqt') ?>">equipment rig management</a>
                            </li>
                            <li class="<?= (preg_match('/^vpoeqt/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/equipment/vpo-eqt') ?>">vpo equipment</a>
                            </li>
                            <li class="<?= (preg_match('/^mvc5vpoeqt/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/equipment/mvc5-vpo-eqt') ?>">MVC5 vpo equipment</a>
                            </li>
                            <li class="<?= (preg_match('/^rentalEqt/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/equipment/rental') ?>">manage rental / company eqt</a>
                            </li>
                            <li class="<?= (preg_match('/^dbkup/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/cronhandler/list') ?>">dashboard backup</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        <a href="<?= $this->baseUrl('/admin/rigs') ?>">rigs</a>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">users<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="<?= (preg_match('/^listall/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/users/listall') ?>">list</a>
                            </li>
                            <li class="<?= (preg_match('/^adminforeman/', $this->activepage)) ? 'active' : '' ?>">
                                <a href="<?= $this->baseUrl('/admin/foremen') ?>">foremen</a>
                            </li>
                        </ul>
                    </li>

                </ul>

                <ul class="nav pull-right">
                    <li class="active">
                        <a href="<?= $this->baseUrl('/admin/') ?>">admin</a>
                    </li>

                    <li>
                        <a href="<?= $this->baseUrl('/') ?>">dashboard</a>
                    </li>

                    <li class="divider-vertical"></li>



                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php //$this->escape($this->currentUser()->getName())  ?>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= $this->baseUrl('users/logout') ?>">logout</a></li>
                            <!-- <li><a href="#">messages</a></li> -->
                        </ul>
                    </li>

                </ul>



            </div>
        </div>
    </div>
</div>
<?php
if (sizeof($_SESSION['lguser']) > 0) {
    $identity = Smapp::getOriginalUser();
    ?>
    <div class="alert alert-error" style="margin-top: -20px">
        <strong>Using Remote login</strong>
        You are currently using remote login for <span style="color: black; font-weight: bold"><?php echo $_SESSION['lguser']['name'] ?>.</span>
        <strong style="cursor: pointer" onclick="unsetSwitchLogin()"> Click to login back as <span style="color: #5915E9; font-weight: bold"><?= $identity['name'] ?></span></strong> 
    </div>
<?php } ?>