<table style="border:1px solid black;" class="table table-striped table-bordered">
    <tbody>
        <tr>
            <td>First Name</td>
            <td>
                <input type="text" id="firstName" class="clsHours required" maxlength="50" value="<?php echo $this->editingPerson[0]['first_name'];?>"/>
                <input type="hidden" id="personId" value="<?php echo $this->editingPerson[0]['id'];?>"/>
                
            </td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td>
                <input type="text" id="lastName" class="clsHours required" maxlength="50" value="<?php echo $this->editingPerson[0]['last_name'];?>"/>
            </td>
        </tr>
        <tr>
            <td>Gender</td>
            <td>
                <select id="gender">
                    <option value="male" <?php echo ($this->editingPerson[0]['gender'] == 'male')?'selected':'';?>>Male</option>
                    <option value="female" <?php echo ($this->editingPerson[0]['gender'] == 'female')?'selected':'';?>>Female</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>Profile img</td>
            <td>
                <input type="text" id="profileImg" class="clsHours required" maxlength="50" value="<?php echo $this->editingPerson[0]['profile_img'];?>"/>
            </td>
        </tr>
        <tr>
            <td>Date of birth</td>
            <td>
                <input type="text" id="dob" class="clsHours required" maxlength="50" value="<?php echo $this->editingPerson[0]['dob'];?>"/>
            </td>
        </tr>
        <tr>
            <td>Occupation</td>
            <td>
                <input type="text" id="occupation" class="clsHours required" maxlength="50" value="<?php echo $this->editingPerson[0]['occupation'];?>"/>
            </td>
        </tr>
        <tr>
            <td>Native place</td>
            <td>
                <input type="text" id="nativePlace" class="clsHours required" maxlength="50" value="<?php echo $this->editingPerson[0]['native_place'];?>"/>
            </td>
        </tr>
        <tr>
            <td>Pet name</td>
            <td>
                <input type="text" id="petName" class="clsHours required" maxlength="50" value="<?php echo $this->editingPerson[0]['pet_name'];?>"/>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center">
                <input type="button" class="btn btn-success btnSavePerson" value="Save"/>
            </td>
        </tr>
        <tr>
            <td colspan="2" style="text-align:center">
                <div class="alert-success clsPAddNotice thumbnail" style="display:none">Person added successfully</div>
            </td>
        </tr>
    </tbody>
</table>