<style scoped>
    .currentjob a{
        /*	display:block;*/
    }
</style>
<?php
$this->headScript()->appendScript('');
?>
<body data-demo-id="chart" data-library="dom">
    <div id="main">
        <div class="demo chart-demo" id="chart-demo">
            <table class="tblAlche" style="text-align: center; margin: 0 auto;">
                <tr>
                    <td colspan="16" class="clsLvl1" nxtCls1="clsLvl2_1" nxtCls2="clsLvl2_2" nextClass="clsLvl2_1">
                        <input type="text" class="input-medium elemLookAt"/>
                        <input type="button" class="btnLookAt btn btn-info" value="Look at"/>
                    </td>
                </tr>
            </table>

            <div class="apiWordsArea">
                <div class="threes secs">

                </div>
                <br/>
                <div class="fours secs">

                </div>
                <br/>
                <div class="fives secs">

                </div>
                <br/>
                <div class="other6 secs"></div>
                <div class="other7 secs"></div>
                <div class="other8 secs"></div>
                <div class="other9 secs"></div>
                <div class="other10 secs"></div>
                <div class="other11 secs"></div>
                <div class="other12 secs"></div>
                <div class="other13 secs"></div>
                <div class="other14 secs"></div>
                <div class="other15 secs"></div>
                <div class="other16 secs"></div>
                <div class="other17 secs"></div>
                <div class="other18 secs"></div>
                <div class="other19 secs"></div>
                <div class="other20 secs"></div>
                <div class="other_more secs"></div>
            </div>

        </div>

    </div>
</body>
